AllCops:
  NewCops: enable
  SuggestExtensions: false
Layout/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/EmptyMethod:
  EnforcedStyle: expanded
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ParameterLists:
  CountKeywordArgs: false
Metrics/MethodLength:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Lint/EmptyClass:
  Enabled: false
